FROM ubuntu:18.04

RUN apt-get update

# python and tensorflow package dependencies
RUN apt-get install -y python3-dev python3-pip \
    && pip3 install -U six numpy wheel mock \
    && pip3 install -U keras_applications==1.0.6 --no-deps \
    && pip3 install -U keras_preprocessing==1.0.5 --no-deps

# install bazel (tensorflow build tool)
RUN apt-get install -y pkg-config zip g++ zlib1g-dev unzip wget libc-ares-dev \
    && wget https://github.com/bazelbuild/bazel/releases/download/0.18.1/bazel-0.18.1-installer-linux-x86_64.sh \
    && chmod +x bazel-0.18.1-installer-linux-x86_64.sh \
    && ./bazel-0.18.1-installer-linux-x86_64.sh

# tensorflow repo
RUN apt-get update \
    && apt-get install -y git \
    && git clone https://github.com/tensorflow/tensorflow.git

RUN ln -s /usr/bin/python3.6 /usr/bin/python

VOLUME ["/out"]

WORKDIR /tensorflow

CMD ["/bin/bash"]